theme: just-the-docs
title: Inventor Pi
description: Making hands-on invention more accessible for teachers and students
logo: "/assets/images/inventor-pi-logo.png"
favicon_ico: "/assets/images/favicon.ico"
